repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: requirements-txt-fixer
    -   id: name-tests-test
        args: [--pytest-test-first ]
- repo: https://github.com/ambv/black
  rev: 22.6.0
  hooks:
    - id: black
- repo: https://github.com/timothycrosley/isort
  rev: 5.10.1
  hooks:
    - id: isort
- repo: https://github.com/asottile/pyupgrade
  rev: v3.2.0
  hooks:
    - id: pyupgrade
- repo: https://github.com/PyCQA/autoflake
  rev: v1.7.7
  hooks:
    - id: autoflake
      args: [ "--in-place", "--remove-all-unused-imports", "--remove-unused-variables", "--expand-star-imports", "--ignore-init-module-imports" ]
      files: \.py$
