# Generated by Django 4.1.3 on 2022-11-03 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="nbr_of_assists",
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name="Number of assists"
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="nbr_of_blocks",
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name="Number of blocks"
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="nbr_of_clearances",
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name="Number of clearances"
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="nbr_of_crosses",
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name="Number of crosses"
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="nbr_of_dispossessed",
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name="Number of dispossessed"
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="nbr_of_dribble_attempts",
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name="Number of dribble attempts"
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="nbr_of_dribble_success",
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name="Number of dribble success"
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="nbr_of_duels",
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name="Number of duels"
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="nbr_of_duels_won",
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name="Number of duels won"
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="nbr_of_fouls_committed",
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name="Number of fouls committed"
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="nbr_of_goals",
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name="Number of goals"
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="nbr_of_goals_conceded",
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name="Number of goals conceded"
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="nbr_of_inside_box_saves",
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name="Number of inside box saves"
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="nbr_of_interception",
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name="Number of interception"
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="nbr_of_key_passes",
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name="Number of key passes"
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="nbr_of_match_played",
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name="Number of match played"
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="nbr_of_minutes_played",
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name="Number of minutes played"
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="nbr_of_passes",
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name="Number of passes"
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="nbr_of_penalty_committed",
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name="Number of penalty committed"
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="nbr_of_penalty_missed",
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name="Number of penalty missed"
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="nbr_of_penalty_scored",
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name="Number of penalty scored"
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="nbr_of_penalty_won",
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name="Number of penalty won"
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="nbr_of_red_cards",
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name="Number of red cards"
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="nbr_of_saves",
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name="Number of saves"
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="nbr_of_shots",
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name="Number of shots"
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="nbr_of_substitute_on_bench",
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name="Number of substitute on bench"
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="nbr_of_substitute_out",
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name="Number of substitute out"
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="nbr_of_tackles",
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name="Number of tackles"
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="nbr_of_woodwork",
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name="Number of woodwork"
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="nbr_of_yellow_cards",
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name="Number of yellow card"
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="passes_accuracy",
            field=models.FloatField(default=0, verbose_name="Passes accuracy"),
        ),
        migrations.AlterField(
            model_name="player",
            name="rating",
            field=models.FloatField(default=0, verbose_name="Rating"),
        ),
    ]
